plugins:
  - jekyll-remote-theme

remote_theme: pages-themes/cayman@v0.2.0

# Load custom CSS
include:
  - _includes/head-custom.html
  - assets/style.css
  - README.md
  - index.md
  - etl_pipeline.md
  - insights.md
  - team_contrib.md
  - about.md

# Load custom CSS for navbar and other tweaks
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      css: /assets/css/style.css

relative_links:
  enabled: true
  collections: true

title: Group 4 Clinical Data ETL with FHIR, SNOMED CT, and HL7 v2
description: This project implements an end-to-end ETL pipeline that extracts clinical data from OpenEMR, transforms it with SNOMED CT concepts, and loads resources into a Primary Care FHIR environment.



